api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BagModelViewSet, ProductModelViewSet

app_name = 'api'

# Initialize the router and register views
router = routers.DefaultRouter()
router.register(r'products', ProductModelViewSet)
router.register(r'bags', BagModelViewSet)

urlpatterns = [
    # Enable routes from the router
    path('', include(router.urls)),
]

orders/urls.py
from django.urls import path

from orders.views import (CanceledTemplateView, OrderCreateView,
                          OrderDetailView, OrderListView, SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-cancel/', CanceledTemplateView.as_view(), name='order_cancel'),
]

products/urls.py
from django.urls import path

from products.views import (FavListView, ProductDetailView, ProductSearchView,
                            ProductsListView, bag_add, bag_remove, fav_add,
                            fav_remove)

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
    path('product/<pk>/', ProductDetailView.as_view(), name='product'),

    # search products by name or description
    path('search/', ProductSearchView.as_view(), name='search_results'),
    path('search/page/<int:page>', ProductSearchView.as_view(), name='search_paginator'),

    # bag
    path('bags/add/<int:product_id>/', bag_add, name='bag_add'),
    path('bags/remove/<int:bag_id>/', bag_remove, name='bag_remove'),

    # favorites
    path('fav/page/<int:page>/', FavListView.as_view(), name='fav_paginator'),
    path('fav/add/<int:product_id>/', fav_add, name='fav_add'),
    path('fav/remove/<int:favorite_id>/', fav_remove, name='fav_remove'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', obtain_auth_token),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from products.views import FavListView
from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('favorite/', FavListView.as_view(), name='favorite'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

products/models.py
import stripe
from django.conf import settings
from django.db import models

from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY


class ProductCategory(models.Model):
    """A model to represent the product category."""
    name = models.CharField(max_length=128, unique=True, help_text='Limit: 128 characters!')
    description = models.TextField(max_length=1024, null=True, blank=True, help_text='Limit: 1024 characters!')

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    """A model representing a product in the store."""
    name = models.CharField(max_length=128, help_text='Limit: 128 characters')
    description = models.TextField(max_length=2048, help_text='Limit: 2048 characters!')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')
    stripe_product_price_id = models.CharField(max_length=128, null=True, blank=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.PROTECT)

    # responsible for additional lines
    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    # Returns a string representation of the product.
    def __str__(self):
        return f'Product: {self.name} || Category: {self.category.name}'

    # method of storing objects in the DB
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        """Overrides the save method of the model."""
        # if stripe-id is not filled then create it
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=None,
                                  update_fields=None)

    def create_stripe_product_price(self):
        """ Creates a product and its price in Stripe."""
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'],
            unit_amount=round(self.price * 100),
            currency="usd"
        )
        return stripe_product_price


class BagQuerySet(models.QuerySet):
    """QuerySet model of Bag"""

    # Calculate total price of all products in bag
    def total_sum(self):
        return sum(bag.sum() for bag in self)

    # Calculate total quantity of all products in bag
    def total_quantity(self):
        return sum(bag.quantity for bag in self)

    # Logic for creating line_items in order.views.OrderCreateView.post
    def stripe_products(self):
        line_items = []
        for bag in self:
            item = {
                'price': bag.product.stripe_product_price_id,
                'quantity': bag.quantity,
            }
            line_items.append(item)
        return line_items


class Bag(models.Model):
    """Bag model"""
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    # QuerySet object as manager
    objects = BagQuerySet().as_manager()

    def __str__(self):
        return f'Bag for {self.user.username} ||| Product for {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

    def de_json(self):
        """Return a dictionary representation of the Bag object that can be serialized to JSON."""
        bag_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum()),
        }
        return bag_item

    @classmethod
    def create_or_update(cls, product_id, user):
        """Create a new Bag object or update the quantity of an existing Bag object."""
        bags = Bag.objects.filter(user=user, product_id=product_id)

        if not bags.exists():
            obj = Bag.objects.create(user=user, product_id=product_id, quantity=1)
            is_created = True
            return obj, is_created
        else:
            bag = bags.first()
            bag.quantity += 1
            bag.save()
            is_crated = False
            return bag, is_crated


class Favorites(models.Model):
    """Favorites model"""
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}'s favorites products."

products/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import HttpResponseRedirect
from django.views.generic import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from common.views import CommonMixin
from products.models import Bag, Favorites, Product, ProductCategory


class IndexView(CommonMixin, TemplateView):
    """Index view that displays the homepage of the website."""
    template_name = 'products/index.html'
    title = 'Hockey - Shop'


class ProductsListView(CommonMixin, ListView):
    """List view that displays the products available in the shop."""
    model = Product
    template_name = 'products/products.html'
    paginate_by = 6
    title = 'Shop - Catalog'

    def get_queryset(self):
        """Override of the `get_queryset` method to filter products by category ID."""
        queryset = super(ProductsListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id).order_by('name') \
            if category_id else queryset.order_by('name')

    def get_context_data(self, *, object_list=None, **kwargs):
        """Override of the `get_context_data` method to add category data to the context."""
        context = super(ProductsListView, self).get_context_data()
        context['categories'] = ProductCategory.objects.all()
        context['category_id'] = self.kwargs.get('category_id')
        return context


class ProductSearchView(CommonMixin, ListView):
    """View for searching products by name or description."""
    model = Product
    template_name = 'products/search_products_by_name.html'
    paginate_by = 6
    title = 'Shop - Catalog'

    def get_queryset(self):
        """Overrides the get_queryset method to filter the Product model queryset
         based on a search query parameter."""
        queryset = super().get_queryset()
        query = self.request.GET.get('query')
        if query is not None and query.strip():
            queryset = queryset.filter(
                Q(name__icontains=query) | Q(description__icontains=query)
            )
        else:
            # if the query is not set, then return an empty QuerySet
            queryset = queryset.none()
        print(queryset)
        return queryset.order_by('name')


class ProductDetailView(CommonMixin, DetailView):
    """View for displaying a single product."""
    model = Product
    template_name = 'products/product.html'
    title = 'Shop - Product card'

    def get_context_data(self, **kwargs):
        """Overrides the get_context_data method to add additional context variables
         for rendering the product template."""
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        return context


@login_required
def bag_add(request, product_id):
    Bag.create_or_update(product_id=product_id, user=request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def bag_remove(request, bag_id):
    bag = Bag.objects.get(id=bag_id)
    bag.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


class FavListView(CommonMixin, ListView):
    model = Favorites
    template_name = 'products/favorites.html'
    title = 'Favorite'
    paginate_by = 6
    queryset = Favorites.objects.all()

    def get_queryset(self):
        """Override the queryset to show the user's favorites only."""
        queryset = super(FavListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id, user=self.request.user) if category_id else queryset.filter(
            user=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        """Add categories and category_id to the context."""
        context = super(FavListView, self).get_context_data()
        context['categories'] = ProductCategory.objects.all()
        context['category_id'] = self.kwargs.get('category_id')
        return context


@login_required
def fav_add(request, product_id):
    product = Product.objects.get(id=product_id)
    favorites = Favorites.objects.filter(user=request.user, product=product)

    if not favorites.exists():
        Favorites.objects.create(user=request.user, product=product)
    else:
        favorite = favorites.first()
        favorite.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def fav_remove(request, favorite_id):
    favorite = Favorites.objects.get(id=favorite_id)
    favorite.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

templates/products/bags.html
{% if bags %}
{% load humanize %}

<h4 class="mt-3 mb-3 Usernamed-flex justify-content-between align-items-center mb-3">
    Bag
    <span class="badge badge-secondary badge-pill">{{ bags.total_quantity }}</span>
</h4>
{% for bag in bags %}
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">{{ bag.product.name }}</h5>
        <p class="card-text">{{ bag.product.description }}</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item bg-light">
            <div class="row text-center">
                <div class="col-lg-4">
                    <input name="basketID" type="number" class="form-control"
                           value="{{ bag.quantity }}" min="0">
                </div>
                <div class="col-lg-4">{{ bag.sum|intcomma }} $</div>
                <div class="col-lg-4">
                    <a href="{% url 'products:bag_remove' bag.id %}">
                        <i class="fas fa-trash"></i>
                    </a>
                </div>
            </div>
        </li>
    </ul>
</div>
{% endfor %}
<div class="card mb-3">
    <div class="card-footer">
        <p class="float-left">Total</p>
        <h4 class="float-right">{{ bags.total_sum|intcomma }} $.</h4>
    </div>
</div>
<a class="btn btn-success btn-lg float-right" href="{% url 'orders:order_create' %}">
    Checkout
</a>

{% else %}
<h4 class="mt-3 mb-3 text-center">Bag is empty</h4>
{% endif %}

templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Hockey Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Catalog <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Profile</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'orders:orders_list' %}">Orders</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:favorite' %}">My favorites</a></li>
                        {% if user.is_superuser or user.is_staff %}
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin panel</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">
                                Log out
                            </a>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Login <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <form class="form-inline my-2 my-lg-0" action="{% url 'products:search_results' %}" method="get">
                        <input class="form-control mr-sm-2" name="query" type="text" placeholder="Search"
                               aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}

<!--Block Footer-->
{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

templates/products/favorites.html
{% extends 'products/base.html' %}
{% load static cache humanize %}

{% block css %}
<link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}




{% block content %}
<div class="container mt-4">

    <div class="row">
        <!-- /.col-lg-3 -->
        <div class="col-lg-9">

            <div class="row">
                {% for favorite in object_list %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ favorite.product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ favorite.product.name }}</a>
                            </h4>
                            <h5>{{ favorite.product.price|intcomma }} $</h5>
                            <p class="card-text">{{ favorite.product.description }}</p>
                            <p class="card-fav">
                                <a href="{% url 'products:fav_remove' favorite.id %}">
                                    Remove from favorites
                                </a>
                            </p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-success" href="#">
                                Send to bag
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

            {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_previous %} {% url 'products:fav_paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    {% for page in paginator.page_range %}
                    <li class="page-item">
                        <a class="page-link"
                           href="{% url 'products:fav_paginator' page %}">
                            {{ page }}
                        </a>
                    </li>
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_next %} {% url 'products:fav_paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
                            Next
                        </a>
                    </li>
                </ul>
            </nav>
            {% endif %}

        </div>

    </div>

</div>
{% endblock %}

templates/products/products.html
{% extends 'products/base.html' %}
{% load static cache humanize %}

{% block css %}
<link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Shop</h1>
            <div class="list-group">
                {% for category in categories %}
                <a href="{% url 'products:category' category.id %}" class="list-group-item">{{ category.name }}
                </a>
                {% endfor %}
            </div>

        </div>

        <!-- /.col-lg-3 -->
        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                             alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                             alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                             alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">

                {% cache 30 object_list page_obj.number category_id %}
                {% for product in object_list %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="{% url 'products:product' product.id %}">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{% url 'products:product' product.id %}">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price|intcomma }} $</h5>
                            <p class="card-text">{{ product.description }}</p>
                            <p class="card-fav">
                                <a href="{% url 'products:fav_add' product.id %}">
                                    Add to favorites
                                </a>
                            </p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-success" href="{% url 'products:bag_add' product.id %}">
                                Send to bag
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% endcache %}

            </div>

            {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_previous %} {% url 'products:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    {% for page in paginator.page_range %}
                    <li class="page-item">
                        <a class="page-link"
                           href="{% url 'products:paginator' page %}">
                            {{ page }}
                        </a>
                    </li>
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_next %} {% url 'products:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
                            Next
                        </a>
                    </li>
                </ul>
            </nav>
            {% endif %}

        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Shop 2023</p>
    </div>
    <!-- /.container -->
</footer>
{% endblock %}

templates/products/search_products_by_name.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}




{% block content %}
<div class="container mt-4">
        {% if not object_list %}
            <h1 class="text-center">There are no matches for your "{{ request.GET.query }}" search.</h1>
        {% else %}
            <!-- /.col-lg-3 -->
        <div class="col-lg-9">
          <h1>Search results: {{ request.GET.query }}</h1>

            <div class="row">
                {% for product in object_list %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="{% url 'products:product' product.id %}">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{% url 'products:product' product.id %}">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }} $</h5>
                            <p class="card-text">{{ product.description }}</p>
                            <p class="card-fav">
                                <a href="{% url 'products:fav_add' product.id %}">
                                    Add to favorite
                                </a>
                            </p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-success" href="{% url 'products:bag_add' product.id %}">
                                Send to bag
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

            {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_previous %} {% url 'products:search_paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    {% for page in paginator.page_range %}
                    <li class="page-item">
                        <a class="page-link"
                           href="{% url 'products:search_paginator' page %}">
                            {{ page }}
                        </a>
                    </li>
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_next %} {% url 'products:search_paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
                            Next
                        </a>
                    </li>
                </ul>
            </nav>
            {% endif %}

        </div>
        {% endif %}
    </div>

</div>
{% endblock %}