api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BagModelViewSet, ProductModelViewSet

app_name = 'api'

# Initialize the router and register views
router = routers.DefaultRouter()
router.register(r'products', ProductModelViewSet)
router.register(r'bags', BagModelViewSet)

urlpatterns = [
    # Enable routes from the router
    path('', include(router.urls)),
]

orders/urls.py
from django.urls import path

from orders.views import (CanceledTemplateView, OrderCreateView,
                          OrderDetailView, OrderListView, SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-cancel/', CanceledTemplateView.as_view(), name='order_cancel'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', obtain_auth_token),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models

from products.models import Bag
from users.models import User


class Order(models.Model):
    """Order model"""
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATES = (
        (CREATED, 'Created'),
        (PAID, 'Paid'),
        (ON_WAY, 'On way'),
        (DELIVERED, 'Delivered'),
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=128)
    address = models.CharField(max_length=256)
    bag_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    state = models.SmallIntegerField(default=CREATED, choices=STATES)
    creator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Order №{self.id}. {self.first_name} {self.last_name}'

    # get json data about the order after payment in bag_history
    # with deleting items from the bag
    def update_after_payment(self):
        bags = Bag.objects.filter(user=self.creator)
        self.state = self.PAID
        self.bag_history = {
            'purchased_items': [bag.de_json() for bag in bags],
            'total_sum': float(bags.total_sum()),
        }
        bags.delete()
        self.save()

orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    """Form for checkout"""
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Name'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Surname'
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email'
    }))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Delivery address'
    }))

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')

orders/views.py
from http import HTTPStatus

import stripe
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from common.views import CommonMixin
from orders.forms import OrderForm
from orders.models import Order
from products.models import Bag

# Assigning Stripe API key from settings
stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessTemplateView(CommonMixin, TemplateView):
    """A view to display the success page for an order."""
    template_name = 'orders/successfully.html'
    title = 'Shop - Thanks for your order!'


class CanceledTemplateView(TemplateView):
    """A view to display the canceled page for an order."""
    template_name = 'orders/canceled.html'


class OrderListView(CommonMixin, ListView):
    """A view to display a list of orders for the current user."""
    template_name = 'orders/orders.html'
    title = 'Store - Orders'
    queryset = Order.objects.all()
    ordering = ('-created',)

    # method to display registered user's orders and not all databases
    def get_queryset(self):
        """Retrieve the orders for the current user."""
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(creator=self.request.user)


class OrderDetailView(DetailView):
    """Displays details of a specific order."""
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        """Returns the context data to be used when rendering the template."""
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        # we cannot inherit from the CommonMixin because we need the actual order number
        context['title'] = f'Store - Order №{self.object.id}'
        return context


class OrderCreateView(CommonMixin, CreateView):
    """Displays a form to create a new order and handles the creation of the order."""
    template_name = 'orders/order_create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')
    title = 'Shop - Ordering'

    # it works to create an object, accept all the data, validate the form, etc.
    def post(self, request, *args, **kwargs):
        """Handles the POST request for creating a new order."""
        # make it so that the logic that creates the order object is executed
        super(OrderCreateView, self).post(request, *args, **kwargs)
        bags = Bag.objects.filter(user=self.request.user)
        # stripe logic
        checkout_session = stripe.checkout.Session.create(
            # what is formed from our order
            line_items=bags.stripe_products(),
            metadata={'order_id': self.object.id},
            mode='payment',
            success_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_success')),
            cancel_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_cancel')),
        )
        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        """Sets the creator of the order to the current user."""
        form.instance.creator = self.request.user
        return super(OrderCreateView, self).form_valid(form)


# from stripe docs
@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']

        # Fulfill the purchase...
        fulfill_order(session)

        # Passed signature verification
    return HttpResponse(status=200)


def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()

templates/orders/canceled.html
<!DOCTYPE html>
<html>
<head>
    <title>Checkout canceled</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
</section>
</body>
</html>

templates/orders/order.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Order №{{ object.id }}</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price</th>
                        <th scope="col">Sum</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for purchased_item in object.bag_history.purchased_items %}
                    <tr>
                        <th scope="row">
                            {{ purchased_item.product_name}}
                        </th>
                        <td>{{ purchased_item.quantity }}</td>
                        <td>{{ purchased_item.price|intcomma }} $</td>
                        <td>{{ purchased_item.sum|intcomma }} $</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <p class="float-right h4 mt-3">Total {{ object.bag_history.total_sum|intcomma }} $</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/orders/order_create.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
<section>
    <div class="alert alert-warning text-center" role="alert">
        Please fill in your email address.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Ordering</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Bag</span>
                    <span class="badge badge-primary badge-pill text-white">{{ bags.total_quantity }}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for bag in bags %}
                    <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div>
                            <h6 class="my-0">{{ bag.product.name }}</h6>
                            <small class="text-muted">{{ bag.quantity }} pcs</small>
                        </div>
                        <span class="text-muted">{{ bag.sum|intcomma }} $</span>
                    </li>
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Amount payable</span>
                        <strong>{{ bags.total_sum|intcomma }} $</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Delivery address</h4>
                <form action="{% url 'orders:order_create' %}" method="post">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="{{ form.first_name.id_for_label }}" class="form-label">Name</label>
                            {{ form.first_name }}
                        </div>

                        <div class="col-sm-6">
                            <label for="{{ form.last_name.id_for_label }}" class="form-label">Surname</label>
                            {{ form.last_name }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.email.id_for_label }}" class="form-label">E-mail address</label>
                            {{ form.email }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.address.id_for_label }}" class="form-label">Address</label>
                            {{ form.address }}
                        </div>

                    </div>

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Continue</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/orders/orders.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Orders</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">State</th>
                        <th scope="col">Created</th>
                        <th scope="col">Total</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in object_list %}
                    <tr>
                        <th scope="row">1</th>
                        <td>{{ order.get_state_display }}</td>
                        <td>{{ order.created|naturaltime }}</td>
                        <td>{{ order.bag_history.total_sum|intcomma }} $</td>
                        <td>
                            <a href="{% url 'orders:order' order.id %}">view</a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/orders/successfully.html
{% extends 'users/base.html' %}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header">
                        <h3 class="text-center font-weight-light my-4">Thanks for your order!</h3>
                    </div>
                    <div class="card-body text-center">
                        <h4>
                            Your order has been successfully generated.
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}